#!/bin/bash
# 一键卸载 intern-clawd
# 用法: bash uninstall.sh
#
# 设计原则:
# - 每个改动前先备份
# - 默认不删 ~/.clawd 知识库（你的笔记是最值钱的，需要二次确认）
# - 自动生成 restore.sh，反悔可以一键回滚
# - 幂等：重复跑不会出错
# - 不程序化操作 macOS Shortcuts.app（风险大），提示手动

set -e

CLAWD_DIR="${CLAWD_DIR:-$HOME/.clawd}"
CLAUDE_DIR="$HOME/.claude"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BACKUP_DIR="$HOME/.clawd-uninstall-backup/$TIMESTAMP"

echo "=== intern-clawd uninstaller ==="
echo "备份目录: $BACKUP_DIR"
echo ""

mkdir -p "$BACKUP_DIR"

# ---- 1. 备份所有要改的文件 ----

echo "[1/8] 备份当前状态..."

if [[ -f "$CLAUDE_DIR/CLAUDE.md" ]]; then
    cp "$CLAUDE_DIR/CLAUDE.md" "$BACKUP_DIR/CLAUDE.md.bak"
    echo "  ✓ ~/.claude/CLAUDE.md"
fi

if [[ -f "$CLAUDE_DIR/settings.json" ]]; then
    cp "$CLAUDE_DIR/settings.json" "$BACKUP_DIR/settings.json.bak"
    echo "  ✓ ~/.claude/settings.json"
fi

if crontab -l >/dev/null 2>&1; then
    crontab -l > "$BACKUP_DIR/crontab.bak"
    echo "  ✓ crontab"
fi

if [[ -f "$HOME/.zshrc" ]]; then
    cp "$HOME/.zshrc" "$BACKUP_DIR/zshrc.bak"
    echo "  ✓ ~/.zshrc"
fi

# ---- 2. 移除全局 CLAUDE.md 的 wiki 同步段 ----

echo ""
echo "[2/8] 移除 ~/.claude/CLAUDE.md 中的 Wiki 同步段..."
if [[ -f "$CLAUDE_DIR/CLAUDE.md" ]] && grep -q "Wiki 知识同步" "$CLAUDE_DIR/CLAUDE.md"; then
    /usr/bin/python3 - "$CLAUDE_DIR/CLAUDE.md" << 'PY'
import sys, re
path = sys.argv[1]
with open(path, encoding="utf-8") as f:
    text = f.read()
# 删除 "## Wiki 知识同步" 到下一个 "## " 之间（含本节）
new = re.sub(r"\n*## Wiki 知识同步[\s\S]*?(?=\n## |\Z)", "\n", text)
new = new.rstrip() + "\n"
with open(path, "w", encoding="utf-8") as f:
    f.write(new)
PY
    echo "  ✓ 已移除"
else
    echo "  - 未找到该段，跳过"
fi

# ---- 3. 移除 settings.json 里 clawd 相关的 hooks ----

echo ""
echo "[3/8] 清理 ~/.claude/settings.json 里的 clawd hooks..."
if [[ -f "$CLAUDE_DIR/settings.json" ]]; then
    /usr/bin/python3 - "$CLAUDE_DIR/settings.json" << 'PY'
import json, sys
path = sys.argv[1]
with open(path, encoding="utf-8") as f:
    data = json.load(f)

removed = 0
hooks = data.get("hooks", {})
for event in list(hooks.keys()):
    new_groups = []
    for group in hooks[event]:
        new_hooks = [
            h for h in group.get("hooks", [])
            if not any(s in str(h.get("command", "")) for s in
                       ["inject-wiki-context", "session-relocate", "permission-router", "mark-session-project"])
        ]
        if new_hooks:
            group["hooks"] = new_hooks
            new_groups.append(group)
        else:
            removed += len(group.get("hooks", []))
    if new_groups:
        hooks[event] = new_groups
    else:
        del hooks[event]
        removed += 1

if not hooks:
    data.pop("hooks", None)

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print(f"  ✓ 移除了 {removed} 个相关 hook 条目")
PY
else
    echo "  - 文件不存在，跳过"
fi

# ---- 4. 删 ~/.claude/hooks/ 里 clawd 相关脚本 ----

echo ""
echo "[4/8] 删除 ~/.claude/hooks/ 里的 clawd 脚本..."
for script in session-relocate.py mark-session-project.sh; do
    if [[ -f "$CLAUDE_DIR/hooks/$script" ]]; then
        cp "$CLAUDE_DIR/hooks/$script" "$BACKUP_DIR/hooks-$script.bak"
        rm "$CLAUDE_DIR/hooks/$script"
        echo "  ✓ 删除 $script（已备份）"
    fi
done

# ---- 5. 移除 cron 里的 reorganize-index ----

echo ""
echo "[5/8] 清理 crontab 里 clawd 相关条目..."
if crontab -l 2>/dev/null | grep -q "reorganize-index.py\|clawd"; then
    crontab -l 2>/dev/null \
      | grep -v "reorganize-index.py" \
      | grep -v "Wiki index reorganize" \
      | grep -v "wiki-maintenance.py" \
      | crontab -
    echo "  ✓ 已移除"
else
    echo "  - 未找到，跳过"
fi

# ---- 6. 移除 ~/.zshrc 的 clawd alias ----

echo ""
echo "[6/8] 清理 ~/.zshrc 的 clawd alias..."
if [[ -f "$HOME/.zshrc" ]] && grep -q "alias clawd\|alias inbox=" "$HOME/.zshrc"; then
    /usr/bin/python3 - "$HOME/.zshrc" << 'PY'
import sys
path = sys.argv[1]
with open(path, encoding="utf-8") as f:
    lines = f.readlines()
keep = [l for l in lines if not (
    "alias clawd=" in l or
    "alias inbox=" in l or
    ".clawd/collect.sh" in l
)]
with open(path, "w", encoding="utf-8") as f:
    f.writelines(keep)
PY
    echo "  ✓ 已移除（重启 terminal 生效）"
else
    echo "  - 未找到，跳过"
fi

# ---- 7. 询问是否删 ~/.clawd 数据 ----

echo ""
echo "[7/8] ~/.clawd 知识库数据..."
if [[ -d "$CLAWD_DIR" ]]; then
    echo "  ⚠️  $CLAWD_DIR 包含你所有的笔记/log/wiki 内容"
    echo "  默认不删。如果确定要删，输入 'delete my notes' 继续："
    read -r CONFIRM
    if [[ "$CONFIRM" == "delete my notes" ]]; then
        mv "$CLAWD_DIR" "$BACKUP_DIR/clawd-data"
        echo "  ✓ 已移到 $BACKUP_DIR/clawd-data（仍可手动还原）"
    else
        echo "  - 保留 ~/.clawd 不动"
    fi
else
    echo "  - ~/.clawd 不存在，跳过"
fi

# ---- 8. 生成 restore.sh ----

echo ""
echo "[8/8] 生成 restore.sh..."
cat > "$BACKUP_DIR/restore.sh" << RESTORE
#!/bin/bash
# Auto-generated by intern-clawd uninstaller at $TIMESTAMP
# 一键还原本次卸载操作
set -e
BACKUP_DIR="$BACKUP_DIR"
CLAUDE_DIR="$CLAUDE_DIR"
CLAWD_DIR="$CLAWD_DIR"

echo "=== intern-clawd restore ==="
echo "从 \$BACKUP_DIR 还原"
echo ""

[[ -f "\$BACKUP_DIR/CLAUDE.md.bak" ]] && cp "\$BACKUP_DIR/CLAUDE.md.bak" "\$CLAUDE_DIR/CLAUDE.md" && echo "  ✓ CLAUDE.md"
[[ -f "\$BACKUP_DIR/settings.json.bak" ]] && cp "\$BACKUP_DIR/settings.json.bak" "\$CLAUDE_DIR/settings.json" && echo "  ✓ settings.json"
[[ -f "\$BACKUP_DIR/crontab.bak" ]] && crontab "\$BACKUP_DIR/crontab.bak" && echo "  ✓ crontab"
[[ -f "\$BACKUP_DIR/zshrc.bak" ]] && cp "\$BACKUP_DIR/zshrc.bak" "\$HOME/.zshrc" && echo "  ✓ ~/.zshrc"

mkdir -p "\$CLAUDE_DIR/hooks"
for s in session-relocate.py mark-session-project.sh; do
    if [[ -f "\$BACKUP_DIR/hooks-\$s.bak" ]]; then
        cp "\$BACKUP_DIR/hooks-\$s.bak" "\$CLAUDE_DIR/hooks/\$s"
        echo "  ✓ hooks/\$s"
    fi
done

if [[ -d "\$BACKUP_DIR/clawd-data" ]]; then
    if [[ -e "\$CLAWD_DIR" ]]; then
        echo "  ⚠️  \$CLAWD_DIR 已存在，跳过数据还原（请手动处理 \$BACKUP_DIR/clawd-data）"
    else
        mv "\$BACKUP_DIR/clawd-data" "\$CLAWD_DIR"
        echo "  ✓ ~/.clawd 数据已还原"
    fi
fi

echo ""
echo "完成。重启 terminal 让 alias 生效。"
RESTORE
chmod +x "$BACKUP_DIR/restore.sh"
echo "  ✓ $BACKUP_DIR/restore.sh"

# ---- 收尾提示 ----

echo ""
echo "=== 卸载完成 ==="
echo ""
echo "下面这些需要手动操作（uninstall.sh 不碰）："
echo "  1. macOS Shortcuts.app: 删除绑定 ⌃⌥C 的「收集到 inbox」shortcut"
echo "  2. ~/.claude-to-im/    : 如果装过手机渠道 bridge，按它自己的 README 卸载"
echo "  3. Mr. Krabs.app       : 如果装过桌面 bubble，从 Applications 里拖到废纸篓"
echo ""
echo "反悔了？跑这个一键还原："
echo "  bash $BACKUP_DIR/restore.sh"
echo ""
